version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: api_mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: api_db
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo

  api:
    build: .
    container_name: api
    restart: always
    ports:
      - "3000:3000"
      - "9229:9229" # Cổng Debug
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app

volumes:
  mongo-data:
